/**
 * Fabula Ultima Companion - 角色卡換色風格模板體系
 * 對齊 NPC 工坊 6 大經典配色風格，嚴格遵守零 Emoji 規範
 */

export const CHARACTER_THEMES = {
  emerald: {
    id: 'emerald',
    name: '翡翠青',
    enName: 'Emerald Forest',
    accent: '#245c45',
    accentHover: '#1c4a37',
    accentDark: '#133829',
    accentLight: '#e1eee7',
    border: '#b2cdbe',
    borderHover: '#245c45',
    cardBorder: 'border-emerald-300',
    cardBorderHover: 'hover:border-emerald-700',
    appBg: '#f3f7f5',
    cardBg: '#ffffff',
    sheetBg: '#f3f7f5',
    panelBg: '#ebf2ee',
    subpanelBg: '#e1ece5',
    headerBg: '#dae6df',
    textDark: '#133829',
    textMuted: '#296048',
    badgeVariant: 'green',
    buttonVariant: 'emerald',
    outlineButtonVariant: 'outline-emerald',
    gradient: 'from-[#245c45] via-[#2c6e53] to-[#1c4a37]',
    chipBg: 'bg-emerald-50 text-emerald-950 border-emerald-300',
    activeTabClass: 'bg-[#245c45] text-white shadow-sm',
    ringColor: 'focus:ring-emerald-700/40 focus:border-emerald-700',
    headerIconColor: 'text-[#245c45]'
  },
  amber: {
    id: 'amber',
    name: '琥珀棕',
    enName: 'Amber Parchment',
    accent: '#9c4d16',
    accentHover: '#823f0f',
    accentDark: '#693108',
    accentLight: '#faeedd',
    border: '#d5c6ad',
    borderHover: '#9c4d16',
    cardBorder: 'border-[#d5c6ad]',
    cardBorderHover: 'hover:border-amber-700',
    appBg: '#f9f6f0',
    cardBg: '#fffdf9',
    sheetBg: '#f9f6f0',
    panelBg: '#f3ebe0',
    subpanelBg: '#ece1d1',
    headerBg: '#e7dac8',
    textDark: '#382012',
    textMuted: '#7b4720',
    badgeVariant: 'gold',
    buttonVariant: 'primary',
    outlineButtonVariant: 'outline',
    gradient: 'from-[#9c4d16] via-[#854112] to-[#693108]',
    chipBg: 'bg-amber-50 text-amber-950 border-amber-300',
    activeTabClass: 'bg-[#9c4d16] text-white shadow-sm',
    ringColor: 'focus:ring-amber-700/40 focus:border-amber-700',
    headerIconColor: 'text-[#9c4d16]'
  },
  blue: {
    id: 'blue',
    name: '群青藍',
    enName: 'Slate Navy',
    accent: '#27527a',
    accentHover: '#1f4263',
    accentDark: '#17324c',
    accentLight: '#dde7f0',
    border: '#b6cad9',
    borderHover: '#27527a',
    cardBorder: 'border-slate-300',
    cardBorderHover: 'hover:border-blue-700',
    appBg: '#f2f5f8',
    cardBg: '#ffffff',
    sheetBg: '#f2f5f8',
    panelBg: '#eaeff4',
    subpanelBg: '#dfe7ee',
    headerBg: '#dae3ec',
    textDark: '#142a3e',
    textMuted: '#2f567b',
    badgeVariant: 'cyan',
    buttonVariant: 'cyan',
    outlineButtonVariant: 'outline-blue',
    gradient: 'from-[#27527a] via-[#33618d] to-[#1f4263]',
    chipBg: 'bg-slate-100 text-slate-900 border-slate-300',
    activeTabClass: 'bg-[#27527a] text-white shadow-sm',
    ringColor: 'focus:ring-blue-700/40 focus:border-blue-800',
    headerIconColor: 'text-[#27527a]'
  },
  crimson: {
    id: 'crimson',
    name: '硃砂紅',
    enName: 'Crimson Wine',
    accent: '#8c2d36',
    accentHover: '#75232b',
    accentDark: '#58171e',
    accentLight: '#f5e6e7',
    border: '#d8bec2',
    borderHover: '#8c2d36',
    cardBorder: 'border-rose-300',
    cardBorderHover: 'hover:border-rose-700',
    appBg: '#f8f4f5',
    cardBg: '#ffffff',
    sheetBg: '#f8f4f5',
    panelBg: '#f2eaec',
    subpanelBg: '#ebdfe2',
    headerBg: '#e6d7db',
    textDark: '#421217',
    textMuted: '#7a2830',
    badgeVariant: 'rose',
    buttonVariant: 'danger',
    outlineButtonVariant: 'outline-crimson',
    gradient: 'from-[#8c2d36] via-[#7b262f] to-[#58171e]',
    chipBg: 'bg-rose-50 text-rose-950 border-rose-300',
    activeTabClass: 'bg-[#8c2d36] text-white shadow-sm',
    ringColor: 'focus:ring-rose-700/40 focus:border-rose-800',
    headerIconColor: 'text-[#8c2d36]'
  },
  purple: {
    id: 'purple',
    name: '秘術紫',
    enName: 'Arcane Plum',
    accent: '#5e387c',
    accentHover: '#4e2c67',
    accentDark: '#3a1f4f',
    accentLight: '#eee5f5',
    border: '#ccbfdb',
    borderHover: '#5e387c',
    cardBorder: 'border-purple-300',
    cardBorderHover: 'hover:border-purple-700',
    appBg: '#f7f4f9',
    cardBg: '#ffffff',
    sheetBg: '#f7f4f9',
    panelBg: '#f1eaf6',
    subpanelBg: '#e9dfef',
    headerBg: '#e3d6ea',
    textDark: '#321646',
    textMuted: '#573373',
    badgeVariant: 'purple',
    buttonVariant: 'purple',
    outlineButtonVariant: 'outline-purple',
    gradient: 'from-[#5e387c] via-[#4d2d66] to-[#3a1f4f]',
    chipBg: 'bg-purple-50 text-purple-950 border-purple-300',
    activeTabClass: 'bg-[#5e387c] text-white shadow-sm',
    ringColor: 'focus:ring-purple-700/40 focus:border-purple-800',
    headerIconColor: 'text-[#5e387c]'
  },
  slate: {
    id: 'slate',
    name: '鐵石灰',
    enName: 'Iron Slate',
    accent: '#404a58',
    accentHover: '#303844',
    accentDark: '#20262f',
    accentLight: '#e6eaef',
    border: '#c0c8d2',
    borderHover: '#404a58',
    cardBorder: 'border-slate-300',
    cardBorderHover: 'hover:border-slate-700',
    appBg: '#f5f6f8',
    cardBg: '#ffffff',
    sheetBg: '#f5f6f8',
    panelBg: '#eceff3',
    subpanelBg: '#e2e6ec',
    headerBg: '#d9dfe6',
    textDark: '#1b212b',
    textMuted: '#3f4956',
    badgeVariant: 'slate',
    buttonVariant: 'slate',
    outlineButtonVariant: 'outline-slate',
    gradient: 'from-[#404a58] via-[#323a45] to-[#20262f]',
    chipBg: 'bg-slate-100 text-slate-900 border-slate-300',
    activeTabClass: 'bg-[#404a58] text-white shadow-sm',
    ringColor: 'focus:ring-slate-700/40 focus:border-slate-800',
    headerIconColor: 'text-[#404a58]'
  }
};

export const STORAGE_THEME_KEY = 'fu_companion_character_theme';

export const getCharacterTheme = (themeId) => {
  if (!themeId || !CHARACTER_THEMES[themeId]) {
    return CHARACTER_THEMES.emerald;
  }
  return CHARACTER_THEMES[themeId];
};
